[package]
name = "rllama"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.47", features = ["derive", "env"] }
encoding_rs = "0.8.35"
gtmpl = "0.7.1"
llama-cpp-2 = "0.1.121"
