[package]
name = "rllama"
version = "0.1.0"
edition = "2024"

[lib]
name = "rllama"
path = "src/lib.rs"

[features]
default = ["tpl-gotpl", "engine-llama-cpp", "engine-hf"]
tpl-gotpl = ["gotpl"]
tpl-minijinja = ["minijinja"]
hw-native = ["llama-cpp-2/native"]
hw-cuda = ["llama-cpp-2/cuda"]
hw-metal = ["llama-cpp-2/metal"]
hw-vulkan = ["llama-cpp-2/vulkan"]
engine-llama-cpp = ["llama-cpp-2", "ggus"]
engine-hf = ["pyo3"]

[dependencies]
clap = { version = "4.5.47", features = ["derive", "env"] }
ggus = { version = "0.5.1", optional = true }
gotpl = { version = "0.2.3", optional = true }
lazy_static = "1.5.0"
llama-cpp-2 = { version = "0.1.121", default-features = false, features = [
    "openmp",
], optional = true }
minijinja = { version = "0.22.0", optional = true }
serde = { version = "1.0.225", features = ["derive"] }
serde_json = "1.0.145"
pyo3 = { version = "0.26.0", optional = true }
dirs = "6.0.0"
walkdir = "2.5.0"
