[package]
name = "rllama"
version = "0.1.0"
edition = "2024"

[lib]
name = "rllama"
path = "src/lib.rs"

[features]
default = ["tpl-gotpl"]
tpl-gotpl = ["gotpl"]
tpl-minijinja = ["minijinja"]

[dependencies]
clap = { version = "4.5.47", features = ["derive", "env"] }
encoding_rs = "0.8.35"
gotpl = { version = "0.2.3", optional = true }
llama-cpp-2 = "0.1.121"
minijinja = { version = "0.22.0", optional = true }
serde = { version = "1.0.225", features = ["derive"] }
serde_json = "1.0.145"
